    const shopData = [
      { id: 1, name: "赤れんが", area: "喜多方（岩月町）", color: "red" },
      { id: 2, name: "ラーメン一平", area: "喜多方（松山町）", color: "red" },
      { id: 3, name: "生江食堂", area: "喜多方（市街地）", color: "red" },
      { id: 4, name: "かど屋・食堂", area: "喜多方（市街地）", color: "red" },
      { id: 5, name: "ラーメンこうへい", area: "喜多方（市街地）", color: "red" },
      { id: 6, name: "老麺まるや", area: "喜多方（市街地）", color: "red" },
      { id: 7, name: "福島屋", area: "喜多方（市街地）", color: "red" },
      { id: 8, name: "たまよし食堂", area: "喜多方（市街地）", color: "red" },
      { id: 9, name: "蔵美", area: "喜多方（市街地）", color: "red" },
      { id: 10, name: "蔵一番やまぐち", area: "喜多方（市街地）", color: "red" },
      { id: 11, name: "こんどう食堂", area: "喜多方（市街地）", color: "red" },
      { id: 12, name: "中華料理 春園", area: "喜多方（市街地）", color: "red" },
      { id: 13, name: "食堂 松", area: "喜多方（市街地）", color: "red" },
      { id: 14, name: "坂内食堂", area: "喜多方（市街地）", color: "red" },
      { id: 15, name: "大三元", area: "喜多方（市街地）", color: "red" },
      { id: 16, name: "たんぽぽ亭", area: "喜多方（市街地）", color: "red" },
      { id: 17, name: "大安食堂", area: "喜多方（市街地）", color: "red" },
      { id: 18, name: "ラーメンSHOPくるくる軒", area: "喜多方（市街地）", color: "red" },
      { id: 19, name: "来夢", area: "喜多方（市街地）", color: "red" },
      { id: 20, name: "いそべ食堂", area: "喜多方（熊倉町）", color: "red" },
      { id: 21, name: "本家大みなと味平", area: "喜多方（関柴町）", color: "red" },
      { id: 22, name: "櫻井食堂", area: "喜多方（市街地）", color: "red" },
      { id: 23, name: "食堂なまえ", area: "喜多方（市街地）", color: "red" },
      { id: 24, name: "大喜", area: "喜多方（関柴町）", color: "red" },
      { id: 25, name: "すがい食堂", area: "喜多方（豊川町）", color: "red" },
      { id: 26, name: "老舗 上海", area: "喜多方（市街地）", color: "red" },
      { id: 27, name: "すがい食堂バイパス店", area: "喜多方（関柴町）", color: "red" },
      { id: 28, name: "あじ庵食堂", area: "喜多方（市街地）", color: "red" },
      { id: 29, name: "塩川屋", area: "喜多方（市街地）", color: "red" },
      { id: 30, name: "麺や玄", area: "喜多方（市街地）", color: "red" },
      { id: 31, name: "中華そば 橙", area: "喜多方（市街地）", color: "red" },
      { id: 32, name: "会津田舎家", area: "喜多方（市街地）", color: "blue" },
      { id: 33, name: "葵飯店", area: "喜多方（市街地）", color: "blue" },
      { id: 34, name: "蔵座敷 あづまさ", area: "喜多方（市街地）", color: "blue" },
      { id: 35, name: "食堂いとう", area: "喜多方（市街地）", color: "blue" },
      { id: 36, name: "うえんで 喜多方店", area: "喜多方（市街地）", color: "blue" },
      { id: 37, name: "ラーメン うめ八", area: "喜多方（市街地）", color: "blue" },
      { id: 38, name: "ウリナム食堂", area: "喜多方（市街地）", color: "blue" },
      { id: 39, name: "中華 栄豊", area: "喜多方（市街地）", color: "blue" },
      { id: 40, name: "ラーメン 喜一", area: "喜多方（関柴町）", color: "blue" },
      { id: 41, name: "きくすい", area: "喜多方（市街地）", color: "blue" },
      { id: 42, name: "喜多屋", area: "喜多方（市街地）", color: "blue" },
      { id: 43, name: "喜多方ラーメン専門店 喜鈴 喜多方店", area: "喜多方（市街地）", color: "blue" },
      { id: 44, name: "けいこのぎょうざや", area: "喜多方（市街地）", color: "blue" },
      { id: 45, name: "香福", area: "喜多方（市街地）", color: "blue" },
      { id: 46, name: "喜多方ラーメン 心美", area: "喜多方（市街地）", color: "blue" },
      { id: 47, name: "台湾料理 広源", area: "喜多方（市街地）", color: "blue" },
      { id: 48, name: "石亭みよし", area: "喜多方（市街地）", color: "blue" },
      { id: 49, name: "せせらぎ食堂", area: "喜多方（市街地）", color: "blue" },
      { id: 50, name: "ちよもと", area: "喜多方（市街地）", color: "blue" },
      { id: 51, name: "道頓堀", area: "喜多方（市街地）", color: "blue" },
      { id: 52, name: "とりそばにこみ和", area: "喜多方（市街地）", color: "blue" },
      { id: 53, name: "とんかつ栄", area: "喜多方（市街地）", color: "blue" },
      { id: 54, name: "ニーハオ", area: "喜多方（市街地）", color: "blue" },
      { id: 55, name: "長谷川食堂", area: "喜多方（市街地）", color: "blue" },
      { id: 56, name: "ラーメン酒場 ばってん", area: "喜多方（市街地）", color: "blue" },
      { id: 57, name: "RAMEN SHOKUDO! ほふるす", area: "喜多方（市街地）", color: "blue" },
      { id: 58, name: "ひさじや食堂", area: "喜多方（市街地）", color: "blue" },
      { id: 59, name: "ひとつぶの麦", area: "喜多方（松山町）", color: "blue" },
      { id: 60, name: "お食事とお酒 舟場α", area: "喜多方（市街地）", color: "blue" },
      { id: 61, name: "満喜", area: "喜多方（市街地）", color: "blue" },
      { id: 62, name: "Là Là Gottsuo", area: "喜多方（市街地）", color: "blue" },
      { id: 63, name: "純手揉み中華 れん", area: "喜多方（市街地）", color: "blue" },
      { id: 64, name: "はせ川", area: "喜多方（松山町）", color: "blue" },
      { id: 65, name: "道の駅喜多の郷 ふるさと亭", area: "喜多方（松山町）", color: "blue" },
      { id: 66, name: "ほおずき", area: "喜多方（松山町）", color: "blue" },
      { id: 67, name: "食堂 ぽんぽこ", area: "喜多方（松山町）", color: "blue" },
      { id: 68, name: "そば処 うちうみ", area: "喜多方（岩月町）", color: "blue" },
      { id: 69, name: "ミセスキャロット信喜亭", area: "喜多方（関柴町）", color: "blue" },
      { id: 70, name: "麺侍", area: "喜多方（市街地）", color: "blue" },
      { id: 71, name: "喜多方ラーメン わんわん", area: "喜多方（関柴町）", color: "blue" },
      { id: 72, name: "さくら亭", area: "喜多方（市街地）", color: "blue" },
      { id: 73, name: "天高盛", area: "喜多方（豊川町）", color: "blue" },
      { id: 74, name: "まつり亭", area: "喜多方（豊川町）", color: "blue" },
      { id: 75, name: "ほまれ食堂", area: "熱塩加納町", color: "blue" },
      { id: 76, name: "大森食堂", area: "熱塩加納町", color: "blue" },
      { id: 77, name: "めん処 縁", area: "熱塩加納町", color: "blue" },
      { id: 78, name: "ごはんやカフェ おぐみ屋", area: "熱塩加納町", color: "blue" },
      { id: 79, name: "アタミ食堂", area: "塩川町", color: "blue" },
      { id: 80, name: "丸市食堂", area: "塩川町", color: "blue" },
      { id: 81, name: "丸萬食堂", area: "塩川町", color: "blue" },
      { id: 82, name: "みさお食堂", area: "塩川町", color: "blue" },
      { id: 83, name: "若竹", area: "塩川町", color: "blue" },
      { id: 84, name: "御食事処 丸市", area: "塩川町", color: "blue" },
      { id: 85, name: "春日遅遅", area: "塩川町", color: "blue" },
      { id: 86, name: "じんべい", area: "山都町", color: "blue" },
      { id: 87, name: "ほがらか食堂", area: "山都町", color: "blue" },
      { id: 88, name: "山都そば処 萬長", area: "山都町", color: "blue" },
      { id: 89, name: "食堂たんぽぽ", area: "山都町", color: "blue" },
      { id: 90, name: "吉田屋", area: "高郷町", color: "blue" },
      { id: 91, name: "味処こまち", area: "高郷町", color: "blue" },
      { id: 92, name: "幸楽苑 喜多方店", area: "喜多方（市街地）", color: "blue" },
      { id: 93, name: "幸楽苑 イオンタウン店", area: "喜多方（塩川町）", color: "blue" },
      { id: 94, name: "はま寿司 喜多方店", area: "喜多方（豊川町）", color: "blue" },
      { id: 95, name: "カラオケレストラン グー 喜多方店", area: "喜多方（市街地）", color: "blue" }
    ];